# Generated by Django 2.1 on 2018-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=123, max_length=11),
            preserve_default=False,
        ),
    ]
