# Generated by Django 2.0.7 on 2018-08-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180824_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='credit',
            field=models.PositiveIntegerField(default=1000000),
        ),
    ]
