# Generated by Django 2.1 on 2018-08-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180816_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.CharField(max_length=255, verbose_name='message')),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
