# Generated by Django 2.1 on 2018-08-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180824_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit',
            field=models.PositiveIntegerField(default=200000),
        ),
    ]
