# Generated by Django 2.1 on 2018-08-21 05:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180820_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bank_account',
            new_name='bank_account_number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=11),
        ),
    ]
