# Generated by Django 2.1 on 2018-08-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180825_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_unvalid',
            new_name='is_invalid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('W', 'wait'), ('D', 'done'), ('F', 'fail')], default='w', max_length=1),
        ),
    ]
