# Generated by Django 2.1 on 2018-08-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180825_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='corroborator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Staff'),
        ),
    ]
