# Generated by Django 2.1 on 2018-08-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact_msg_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='not important', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=100000, verbose_name='message'),
        ),
    ]
